repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.2.3
    hooks:
    - id: flake8
      additional_dependencies: [
        "flake8-bugbear",
        "flake8-import-order",
        "flake8-tidy-imports",
        "flake8-todo",
        "flake8-string-format"
      ]