jobs:
- job: lint
  displayName: 'Lint'

  pool:
    vmImage: 'ubuntu-18.04'

  variables:
    PIP_CACHE_DIR: ".cache/pip"

  steps:
  - task: UsePythonVersion@0
    displayName: 'Set Python version'
    inputs:
      versionSpec: '3.7.x'
      addToPath: true

  - script: pip install .[dev]
    displayName: 'Install project and dev dependencies'

  - script: python -m flake8
    displayName: 'Run linter'
