name: Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9, "3.10", "3.11"]
        django: [3.2.*, 4.0.*, 4.1.*]
        crispy-forms: [2.0.*]
        exclude:
          - python-version: 3.7
            django: 4.0.*
          - python-version: 3.7
            django: 4.1.*
          - python-version: "3.11"
            django: 3.2.*
          - python-version: "3.11"
            django: 4.0.*
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip
          cache-dependency-path: setup.py
      - name: Install dependencies
        run: |
          pip install -e .[test]
          pip install django==${{ matrix.django }}
          pip install django-crispy-forms==${{ matrix.crispy-forms }}
      - name: Run tests
        run: |
          pytest
